name: test

on: [push]

jobs:
  phpunit:
    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: |
          composer install
      - name: Run test
        run: composer phpunit
